services:
  - name: saelor
    type: web
    env: python
    repo: https://github.com/dnilasor/saleor
    buildCommand: pip3 install -r requirements.txt && python manage.py migrate --no-input
    startCommand: ./render-start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: saleor.settings
      - key: DEBUG
        value: True
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@example.com
      - key: ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: saelor-db
          property: connectionString
      - key: REDIS_URL
        fromService: 
          type: redis
          name: saelor-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0
#      - key: ALLOWED_CLIENT_HOSTS
#        value: "*"
#        - key: AWS_MEDIA_BUCKET_NAME
#          value: 
#        - key: AWS_ACCESS_KEY_ID
#          value:
#        - key: AWS_SECRET_ACCESS_KEY
#          value: 
  - type: redis
    name: saelor-redis
    ipAllowList: [] # only allow internal connections


databases:
    - name: saelor-db
      ipAllowList: [] # only allow internal connections

# python manage.py migrate && python manage.py populatedb --createsuperuser --withoutimages